"""
Django settings for Django9 project.

Generated by 'django-admin startproject' using Django 2.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from django.urls.base import reverse_lazy
from django.conf.global_settings import AUTHENTICATION_BACKENDS
#reverse_lazy : 기능은 reverse와 동일.
Login_URL = reverse_lazy('auth:signin')

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


SOCIAL_AUTH_GOOGLE_OAUTH2_KEY='747523225313-227t3ljpqe5hpsimr4j3tfqa6rlui46j.apps.googleusercontent.com'
#구글에서 발급받은 클라이언트 ID
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET='nBX0nk0hXw2bPnT0tg3kDslr'
#구글에서 발급받은 보안 비밀
AUTHENTICATION_BACKENDS = (
    'social_core.backends.open_id.OpenIdAuth',
    'social_core.backends.google.GoogleOpenId',
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
    
    
    
    )
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&ok9#s$hje0-t0yx&j+sr4$s941pb26!d%cx0usyng*q+6)@-p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
#클라이언트가 웹서버에게 요청할 때 허용할 도메인이름
#아무것도 적지않은경우 '127.0.0.1'로만 요청가능
ALLOWED_HOSTS = ['127.0.0.1','localhost','pythonanywhere.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookmark',
    'vote',
    'customlogin',
    'social_django', #소셜 로그인에 대한 어플리케이션
    #python에 social_auth_app_django 모듈이 설치되야함
    'blog',
    'disqus', #댓글 사이트와 연동하기 위한 어플리케이션
    'django.contrib.sites',
    
    
    
]
DISQUS_WEBSITE_SHORTNAME = 'bazzi-1'
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Django9.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'Django9.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'ko'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

#URL 주소로 파일 주소를 접근할때 사용하는 경로
MEDIA_URL = '/files/'
#실제로 이미지/파일/동영상/한글/파워포인트가 저장되는 경로
MEDIA_ROOT = os.path.join(BASE_DIR,'files') #src폴더에 files폴더안에 미디어파일을 저장

